version: '3.1'
services:
  api:
    image: areeb/api
    build: ./api
    ports:
      - '9090:9090'
    depends_on:
      - db
    environment:
      - FRONTEND_URL=http://localhost
      - EXPRESS_SERVER_PORT=9090
      - PG_USER=postgres
      - PG_HOST=db
      - PG_DATABASE=postgres
      - PG_PASS=anypass
      - PG_PORT=5432
      - PASSWORD_SALT_ROUND=10
    links:
      - "db"
  app:
    image: areeb/app
    build: ./app
    ports:
      - '80:80'
    depends_on:
      - api
  db:
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=anypass
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
networks:
  samenetwork:
    driver: bridge