version: '3.1'
services:
  app:
    image: areeb/app
    build: ./app
    ports:
      - '80:80'
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: anypass
    volumes: 
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
